services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - CADDY_ADMIN=127.0.0.1:2019
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"